## Series 클래스

In [1]:
import pandas as pd

In [2]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [3]:
# 인덱스값만 출력
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [4]:
# 자료값만 출력
print(s.values)

[1 3 5 7 9]


In [5]:
# 인덱스를 지정하여 인덱스와 자료값 출력
s = pd.Series([9904312, 3448737, 2890451, 2466052], 
              index = ['서울', '부산', '인천', '대구'])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [6]:
# dtype = 'str' : 인덱스의 데이터타입이 문자열임을 알려줌
print(s.index)

Index(['서울', '부산', '인천', '대구'], dtype='str')


In [7]:
print(s.values)

[9904312 3448737 2890451 2466052]


In [8]:
# 데이터의 이름 설정
s.name = '인구'
# 인덱스의 이름 설정
s.index.name = '도시'
print(s)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [9]:
# 인덱스 이름 삭제
s.index.name = None
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64


In [10]:
print(pd.Series(range(1, 5)))

0    1
1    2
2    3
3    4
dtype: int64


In [11]:
# 81000의 경우 데이터 타입이 object이므로 연산에 바로 사용할 수 없다
# 연산에 사용할 경우 데이터 타입의 변형이 우선적으로 필요하다
s = pd.Series(['samsung', 81000])
print(s)

0    samsung
1      81000
dtype: object


In [12]:
from pandas import Series

data = [1000, 2000, 3000]
s = Series(data)
print(s.index)
# index.to_list 메서드를 사용하면 인덱스를 리스트 형태로 출력 가능
print(s.index.to_list())

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [13]:
data = [1000, 2000, 3000]
# 각 데이터에 정수 인덱스가 자동으로 부여
s = Series(data)
# 인덱스를 입력한 값으로 변경
s.index = ['메로나', '구구콘', '하겐다즈']
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [14]:
data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
# s = Series(data=data, index=index)
# s = Series(data, index=index)
# s = Series(index=index, data=data) 모두 실행 가능
# s = Series(data=data, index) 일반매개변수 앞에 키워드매개변수가 올 수 없으므로 실행 불가능
s = Series(data, index)
print(s)

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64


In [15]:
# reindex 메서드 : 인덱스의 이름을 재설정 
#                  -> 이전에 없던 인덱스 생성 시 자료값이 None으로 생성되어 삽입
#                  -> 이 경우 dtype이 float으로 변경됨
s2 = s.reindex(['메로나', '비비빅', '구구콘'])
print(s2)

메로나    1000.0
비비빅       NaN
구구콘    2000.0
dtype: float64


In [16]:
# fillna 메서드 : 자료값이 None인 인덱스를 찾아 자료값을 0으로 채운다
s2 = s2.fillna(0)
print(s2)

메로나    1000.0
비비빅       0.0
구구콘    2000.0
dtype: float64


In [17]:
price = [42500, 42550, 41800, 42550, 42650]
# date와 같이 인덱스 값에 연,월,일 등 날짜 또는 시간 형태의 값이 입력되면 이것을 시계열 데이터라고 함
date = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = Series(price, date)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [18]:
# 데이터가 딕셔너리 형태인 경우 key는 인덱스로, value는 자료값으로 사용
data = {
    '2019-05-31' : 42500,
    '2019-05-30' : 42550,
    '2019-05-29' : 41800,
    '2019-05-28' : 42550,
    '2019-05-27' : 42650
}
s = Series(data)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [19]:
print(s.index)

Index(['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27'], dtype='str')


In [20]:
# index.dtype : 인덱스의 데이터 타입을 확인
print(s.index.dtype)

str


In [21]:
print(s.values)

[42500 42550 41800 42550 42650]


## Series indexing

In [22]:
s1 = Series([10, 20, 30])
s2 = Series([10, 20, 30], index=[1, 2, 3])

print(s1[0])
# print(s2[0]) : 존재하지 않는 인덱스로 접근하기 때문에 에러 발생
print(s2[1])

10
10


In [23]:
s3 = Series([10, 20, 30], index=['a', 'b', 'c'])
# 딕셔너리에 접근하듯이 key-value 형식으로 접근
print(s3['a'])

10


In [24]:
print(s3.index[0])
print(s3.index[-1])

a
c


## Series Slicing

In [25]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=['서울', '부산', '인천', '대구'])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [26]:
# 행 인덱싱이 아닌 행 위치 인덱싱을 이용하여 슬라이싱
# 마지막 3번 위치는 출력 X
print(s[1:3])

부산    3448737
인천    2890451
dtype: int64


In [27]:
# 행 인덱싱 '라벨'을 이용하여 슬라이싱
# '부산'부터 '대구'까지 모두 출력
print(s['부산':'대구'])

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [28]:
print(s[1:])

부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [29]:
print(s[:-1])

서울    9904312
부산    3448737
인천    2890451
dtype: int64


In [30]:
print(s[:2])

서울    9904312
부산    3448737
dtype: int64


In [31]:
s1 = pd.Series(range(3), index=['a', 'b', 'c'])
s1

a    0
b    1
c    2
dtype: int64

In [32]:
# 속성 스타일
print(s1.a)

0


In [33]:
# key 형식 사용
print(s1['a'])

0


In [34]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=['서울', '부산', '인천', '대구'])
print(s)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [35]:
# 딕셔너리 자료형에서 제공하는 in 연산이 사용 가능
print('대구' in s)

True


In [36]:
print('대전' in s)

False


In [37]:
# items 메서드를 사용하면 for 루프를 통해 각 원소의 키(key)와 값(value)에 접근 가능
for key, value in s.items():
    print('%s : %d' %(key, value))

서울 : 9904312
부산 : 3448737
인천 : 2890451
대구 : 2466052


In [38]:
s2 = pd.Series({'서울' : 9631482, '부산' : 3393191, '인천' : 2632035, '대전' : 1490158})
print(s2)

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64


In [39]:
# 인덱스에서 배치한 순서대로 결과 출력
s2 = pd.Series({'서울' : 9631482, '부산' : 3393191, '인천' : 2632035, '대전' : 1490158},
               index=['부산', '서울', '인천', '대전'])
print(s2)

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64


In [40]:
from pandas import Series

data = [1000, 2000, 3000]
index = ['메로나', '구구콘', '하겐다즈']
s = Series(data, index)
s

메로나     1000
구구콘     2000
하겐다즈    3000
dtype: int64

In [41]:
# iloc : 위치 인덱스를 이용
print(s.iloc[0:2])

메로나    1000
구구콘    2000
dtype: int64


In [42]:
# loc : 라벨 인덱스를 이용
print(s.loc['메로나':'구구콘'])

메로나    1000
구구콘    2000
dtype: int64


In [43]:
indice = [0, 2]
print(s.iloc[indice])

메로나     1000
하겐다즈    3000
dtype: int64


In [44]:
print(s.iloc[[0, 2]])

메로나     1000
하겐다즈    3000
dtype: int64


In [45]:
indice = ['메로나', '하겐다즈']
print(s.loc[indice])
print(s.loc[['메로나', '하겐다즈']])

메로나     1000
하겐다즈    3000
dtype: int64
메로나     1000
하겐다즈    3000
dtype: int64


In [46]:
# 라벨 인덱스를 사용하여 값 수정
# s.iloc[0] = 500
# s[메로나] = 500 모두 사용 가능
s.loc['메로나'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
dtype: int64


In [47]:
# 새로운 값 삽입
s.loc['비비빅'] = 500
print(s)

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


In [48]:
# drop : 기존에 존재하던 값 삭제
s1= s.drop('메로나')
print(s1)
print()
# 기존의 Series는 변화 X
print(s)

구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64

메로나      500
구구콘     2000
하겐다즈    3000
비비빅      500
dtype: int64


## Series 연산

In [49]:
s1 = pd.Series([9904312, 3448737, 2890451, 2466052],
               index=['서울', '부산', '인천', '대구'])
s2 = pd.Series({'서울' : 9631482, '부산' : 3393191, '인천' : 2632035, '대전' : 1490158},
               index=['부산', '서울', '인천', '대전'])
ds = s1 - s2
print(ds)

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [50]:
# 브로드캐스팅 연산 : 모든 값들에 연산이 각각 적용
s3 = s1 / 1000000
print(s3)

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64


In [51]:
# 값만 가져와서 같은 자리에 있는 값 끼리 연산 수행
print(s1.values - s2.values)

[ 6511121 -6182745   258416   975894]


In [52]:
# notnull() : 자료값이 null이 아닌 부분(T/F) -> 데이터 필터링에 사용
# ds[ds.notnull()] : notnull에서 True인 부분만 추출
print(ds[ds.notnull()])

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [53]:
rs = (s1 - s2) / s2 * 100
print(rs)

대구         NaN
대전         NaN
부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [54]:
rs = rs[rs.notnull()]
print(rs)

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [55]:
rs['부산'] = 1.63     # 기존에 존재하던 값이 있으므로 값을 수정
rs['대구'] = 1.41     # 기존에 존재하던 값이 없으므로 새로운 값을 추가
print(rs)

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64


In [56]:
del rs['서울']       # 기존에 존재하던 값을 삭제
print(rs)

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64


In [57]:
from pandas import Series

date = ['6/1', '6/2', '6/3', '6/4', '6/5']
high = Series([42800, 42700, 42050, 42950, 43000], index=date)
low = Series([42150, 42150, 41300, 42150, 42350], index = date)
print(high)
print('------------')
print(low)

6/1    42800
6/2    42700
6/3    42050
6/4    42950
6/5    43000
dtype: int64
------------
6/1    42150
6/2    42150
6/3    41300
6/4    42150
6/5    42350
dtype: int64


In [58]:
diff = high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [59]:
# 가장 큰 값
print(diff.max())
# 가장 큰 값의 위치
print(diff.idxmax())

800
6/4


In [60]:
data = {
    '삼성전자' : '전기, 전자',
    'LG전자' :  '전기, 전자',
    '현대차' : '운수장비',
    'NAVER' : '서비스업',
    '카카오' : '서비스업'
}
s = Series(data)
print(s)

삼성전자     전기, 전자
LG전자     전기, 전자
현대차        운수장비
NAVER      서비스업
카카오        서비스업
dtype: str


In [61]:
# 값들 중 중복을 제거하고 값을 출력
print(s.unique())

<StringArray>
['전기, 전자', '운수장비', '서비스업']
Length: 3, dtype: str


In [62]:
# 동일한 값이 몇 개 존재하는지 카운트해서 그 값을 출력
print(s.value_counts())

전기, 전자    2
서비스업      2
운수장비      1
Name: count, dtype: int64


In [63]:
import pandas as pd
# numpy : 수치 연산을 잘 하기 위해 사용하는 lib
#         특히 행렬 연산에 강세를 보임
import numpy as np

s = pd.Series(['선화', '강호', np.nan, '소정', '우영'])
print(s)

0     선화
1     강호
2    NaN
3     소정
4     우영
dtype: str


In [64]:
# 자료값이 Null인지 출력(T/F)
s.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [65]:
# 자료값이 None인지 출력(T/F)
s.isna()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [66]:
s[s.isnull()]

2    NaN
dtype: str

In [67]:
s[s.notnull()]

0    선화
1    강호
3    소정
4    우영
dtype: str

In [68]:
def remove_comma(x):
    # replace(',', '') : ','를 ''으로 대체
    return int(x.replace(',', ''))

In [69]:
s = Series(['1,234', '5,678', '9,876'])
# pandas에서 map 함수는 반복자 객체가 따로 주어지지 않고, Series가 가진 객체의 수 만큼 객체를 차례로 호출하게 됨
result = list(s.map(remove_comma))
print(result)

[1234, 5678, 9876]


In [70]:
from pandas import Series

data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27',]
s = Series(data, index)
print(s)

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [71]:
# cond : 조건식에 해당
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [72]:
# s[cond] = s[s>42000]
print(s[cond])

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64


In [73]:
from pandas import Series

data = [3.1, 2.0, 10.1, 5.1]
index = ['00010', '00020', '00030', '00040']
s = Series(data, index)
print(s)

00010     3.1
00020     2.0
00030    10.1
00040     5.1
dtype: float64


In [74]:
# Series 객체의 자료값을 기준으로 오름차순으로 정렬
# ascending=False : 내림차순으로 정렬
s1 = s.sort_values(ascending = False)
print(s1)

00030    10.1
00040     5.1
00010     3.1
00020     2.0
dtype: float64


In [78]:
# 자료 값(원데이타)을 기준으로 인덱스 값을 오름차순으로 정렬
# ascending=True : 기본값
# ascending=False : 내림차순으로 정렬
s2 = s.rank()
print(s2)

00010    2.0
00020    1.0
00030    4.0
00040    3.0
dtype: float64


In [76]:
s2 = s.rank(ascending=False)
print(s2)

00010    3.0
00020    4.0
00030    1.0
00040    2.0
dtype: float64
